### ISSUE TITLE
能否增加hook字段，便于编译型的语言在部署前进行构建

### ISSUE THREAD

**Issue by ShadowWaIker** [serverless-components/tencent-scf#21]
可否增加类似于website-component的[hook字段](https://github.com/serverless-components/tencent-fullstack/blob/57d1b6a7d35d6e384c18a4fecc1f00e388dc5072/frontend/serverless.yml#L13)，用于处理go之类的编译型语言在上传前的构建操作。

这样的hook字段对于解释型语言应该也会很有用，例如可以配置切换node的依赖包(某些有二进制依赖，本地的依赖跟云函数不能通用的场景): mv node_modules  node_modules_local; mv node_modules_scf node_modules;

**Comment by anycodes** [comment]
v2版本可能不能增加，v1版本已经逐渐的hold住，向v2转移了‘

**Comment by yugasun** [comment]
@ShadowWaIker V2 版本已经支持 hook，但是需要跟 `dist` 一起配置使用，如下：

```yaml
org: orgDemo
app: appDemo
stage: dev
component: scf
name: scfDemo

inputs:
  src:
        hook: npm run build
        dist: ./dist # npm run build 之后生成的需要部署的目录
  runtime: Nodejs10.15
  region: ap-guangzhou
  namespace: test
  handler: index.main_handler
```
