### ISSUE TITLE
上传代码时报错

### ISSUE THREAD

**Issue by TMaize** [serverless-components/tencent-scf#26]
错误信息
The "path" argument must be of type string. Received type object

Tencent Serverless Toolkit for VS Code版本为v2.0.2

serverless.yaml配置如下

```yaml
src:
  src: './'
  exclude:
    - 'node_modules/**'
```

**Comment by ycp424c** [comment]
vs code 插件支持component v2的规范，按这个规范写serverless.yaml试试
https://github.com/serverless-components/tencent-scf/blob/v2/doc/configure.md

**Comment by TMaize** [comment]
就是按照文档写的，发现好像只支持第一种写法

![1592374546(1)](https://user-images.githubusercontent.com/16556693/84862417-bde1b680-b0a5-11ea-8575-e3354d86f11b.png)

**Comment by ycp424c** [comment]
完整yaml贴一下看看

**Comment by TMaize** [comment]
```yaml
app: render
component: scf
inputs:
  cls:
    logsetId: ''
    topicId: ''
  description: 使用puppeteer渲染图片和pdf
  enableRoleAuth: true
  events:
    - apigw:
        name: SCF_API_Service
        parameters:
          endpoints:
            - function:
                functionQualifier: $LATEST
                isIntegratedResponse: true
              method: ANY
              path: /render
          environment: test
          protocols:
            - http
            - https
          serviceId: service-px5t89qd
  handler: index.main_handler
  memorySize: 768
  name: render
  namespace: default
  region: ap-shanghai
  runtime: Nodejs12.16
  src:
    src: './'
    exclude:
      - 'node_modules/**'
  timeout: 900
  vpcConfig:
    subnetId: ''
    vpcId: ''
name: ap-shanghai_default_render
org: '1252268527'
stage: dev
# For more information: https://github.com/serverless-components/tencent-scf/blob/v2/doc/configure.md
```
