### ISSUE TITLE
serverless.yml 开启固定IP未生效

### ISSUE THREAD

**Issue by roy-lau** [serverless-components/tencent-scf#28]
我的 serverless.yml 配置如下
```yml
# 参考文档 https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
name: wechat-official-accounts # (必选) 组件实例名称.
component: koa # (必填) 该组件创建的实例名称
app: wechat-official-accounts # (可选) 用于记录组织信息. 默认与name相同，必须为字符串
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  functionName: sls-wechat-official-accounts # 云函数名称
  namespace: sls # 云函数命名空间
  description: serverless无服务器云函数，使用的koa模板，用于微信公众号。 # 云函数描述
  serviceName: sls_wechat_gateway # api网关服务名称
  bucket: sls-wechat-official-accounts-bucket  # bucket name，当前会默认在bucket name后增加 appid 后缀
  src:
    src: ./  # 本地需要打包的文件目录
    exclude: # 被排除的文件或目录
      - .env
  runtime: Nodejs10.15 # 云函数的运行时环境。除 Nodejs10.15 外，可选值为：Python2.7、Python3.6、Nodejs6.10、Nodejs8.9、Nodejs12.16、PHP5、PHP7、Golang1、Java8。
  region: ap-beijing
  eip: true # true/false 是否开启固定IP
  apigatewayConf:
    protocols:
      - http
      - https
    environment: test
```
![image](https://user-images.githubusercontent.com/22829291/89256327-71066f00-d656-11ea-8297-a496bb46b784.png)

控制台查看如下：

![image](https://user-images.githubusercontent.com/22829291/89256383-8d0a1080-d656-11ea-8b3e-2a6378ab913a.png)

![image](https://user-images.githubusercontent.com/22829291/89256429-ae6afc80-d656-11ea-8257-942e9fdf9f39.png)

请问是我 `eip: true` 配置的不对？还是什么问题？

**Comment by yugasun** [comment]
你好，当然只有 `scf` 组件支持 `eip` 配置，其他组件不支持该配置。

**Comment by roy-lau** [comment]
> 你好，当然只有 `scf` 组件支持 `eip` 配置，其他组件不支持该配置。

有计划对 `koa` 或其他组件支持 `eip` 配置吗？

**Comment by yugasun** [comment]
8.15 号之前会针对框架级组件统一支持

**Comment by roy-lau** [comment]
多谢告知，午安！:smile:

**Comment by yugasun** [comment]
@roy-lau 当前 koa 组件已支持，只需要配置 `functionConf.eip` 为 `true`，如下：

```yaml
component: koa
name: koaDemo

inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs10.15
  functionConf:
    # 固定出口 IP
    eip: true
```
