### ISSUE TITLE
ts 打包到 dist 目录下如何部署，node_modules 怎么处理。带带弟弟🥺

### ISSUE THREAD

**Issue by 0jinxing** [serverless-components/tencent-scf#80]
## 项目结构

```bash
.
├── dist
│   ├── index.js
│   ├── mail.js
│   ├── notion.js
│   └── parser.js
├── node_modules
├── package.json
├── serverless.yml
├── src
│   ├── index.ts
│   ├── mail.ts
│   ├── notion.ts
│   └── parser.ts
├── tsconfig.json
└── yarn.lock
```

## serverless.yaml

```yaml
name: my-bills
component: scf

inputs:
  src: ./
  handler: index.main_handler
  region: ap-guangzhou
  runtime: Nodejs10.15
  memorySize: 128
  timeout: 3
  type: event
  events:
    - timer:
        name: timer
        parameters:
          cronExpression: "0 0 6 * *"
          enable: true
```

handler 函数 在 dist/index.main_handler。
